config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users' => 'users#index'
  get '/posts' => 'posts#show'
  resources :postusers, only: [:create]
  resources :posts, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: { minimum: 10, maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @posts = Post.all.includes(:user)
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to '/posts/show'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/postusers_controller.rb
#usersをdbへインサートするためのpost処理コントローラ

class PostusersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/users'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :age, :intro)
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorials Sample App"

    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/show.html.erb
<h1>POSTS</h1>

<div>
     <% @posts.each do |post| %>
        <div>
          <%= post.id%>.
          <%= post.user.name %>
          <br />
          <br />
          <%= post.content %>
          <br />
          ================================================
        </div>
     <% end %>
</div>


<%= form_with model:Post.new do |form| %>
  <% if Post.new.errors.any? %>
    errors
  <% end %>

  <%= form.label :user_id %>
  <%= form.text_field :user_id %>

  <br/>
  <%= form.label :content %>
  <%= form.text_area :content%>

  <br/><br/>
  <%= form.submit "送信"%>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      is a <a href="https://railstutorial.jp/#ebook">book</a> and
      <a href="https://railstutorial.jp/#screencast">screencast</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>  Get help on the Ruby on Rails Tutorial at the
      <a href="https://railstutorial.jp/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="https://railstutorial.jp/#ebook">
      <em>Ruby on Rails Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title)%> | Ruby on Rails Tutorial Sample App</title>
    </head>
    <body>
        <h1>Sample Sample App</h1>
        <p>
            This is the home page for the
            <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
            sample application.
    </p>
    </body>
</html>

app/views/users/index.html.erb
<h1>USERS</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.id %>,<%= user.name %>, <%= user.age %>, <%= user.intro %></li>
  <% end %>
</ul>

<%= form_with(url: postusers_path, method: "post", model: User.new)  do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br/>
  <%= form.label :age %>
  <%= form.text_field :age%>

  <br/>
  <%= form.label :intro %>
  <%= form.text_field :intro %>

  <br/><br/>
  <%= form.submit "送信"%>
<% end %>